projects:
  mytasksapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
